// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_stage_6 = "CgkI3IC9vIEPEAIQBw"; // <GPGSID>
        public const string achievement_its_a_starlight_attack = "CgkI3IC9vIEPEAIQBA"; // <GPGSID>
        public const string achievement_its_getting_stronger = "CgkI3IC9vIEPEAIQDA"; // <GPGSID>
        public const string achievement_level_up = "CgkI3IC9vIEPEAIQBQ"; // <GPGSID>
        public const string achievement_disassemble = "CgkI3IC9vIEPEAIQCw"; // <GPGSID>
        public const string achievement_level_6 = "CgkI3IC9vIEPEAIQBg"; // <GPGSID>
        public const string leaderboard_stage = "CgkI3IC9vIEPEAIQDg"; // <GPGSID>
        public const string achievement_its_the_boss = "CgkI3IC9vIEPEAIQAw"; // <GPGSID>
        public const string achievement_upgrade_complete = "CgkI3IC9vIEPEAIQDQ"; // <GPGSID>
        public const string achievement_600_score = "CgkI3IC9vIEPEAIQCQ"; // <GPGSID>
        public const string achievement_60_score = "CgkI3IC9vIEPEAIQCA"; // <GPGSID>
        public const string achievement_6000_score = "CgkI3IC9vIEPEAIQCg"; // <GPGSID>
        public const string leaderboard_best_score = "CgkI3IC9vIEPEAIQAg"; // <GPGSID>

}

